### ISSUE TITLE
Add the eventing source label to indicate the source type

### ISSUE THREAD

**Issue by houshengbo** [knative-sandbox/eventing-gitlab#141]
**Describe the bug**
All eventing sources should have a label to indicate the source type for all the released resources.
The similar label is `networking.knative.dev/ingress-provider` for all the serving ingresses.
I propose to add the label `contrib.eventing.knative.dev/source-provider` for all the available resources.
Since this repository is for eventing-gitlab, we will use `contrib.eventing.knative.dev/source-provider: gitlab`.

 **Expected behavior**
Add the label `contrib.eventing.knative.dev/source-provider: gitlab` for all resources.

 **Knative release version**
main

 **Additional context**
Facilitate the support in knative operator

**Comment by antoineco** [comment]
Xref-ing the discussion in https://github.com/knative-sandbox/eventing-github/issues/149
