### ISSUE TITLE
SSL issues with self-hosted GitLab instance

### ISSUE THREAD

**Issue by goldmann** [knative-sandbox/eventing-gitlab#171]
I would like to understand how we can configure GitLab event source with a self-hosted instance of GitLab for example with a certificate issued by our own CA. I see there is a `sslverify` field in the CRD, but it suggest that the SSL verification can be turned on or off for the webhook itself. The problem I'm facing is the API endpoint itself though:

```
message: 'failed to add webhook to the project "XYZ/knative-eventing-source"
      due to an error: Post "https://gitlab.XXXX.com/api/v4/projects/XYZ%2Fknative-eventing-source/hooks":
      x509: certificate signed by unknown authority '
```

Ideally we would need to provide a CA bundle so that the connection can be verified properly.

I'm using currently v0.21, but I'm unsure if it matters.

**Comment by antoineco** [comment]
Good point, the spec doesn't currently expose attributes to configure secure communications with the GitLab API.

As a workaround, you could mount your CA certificate/bundle inside the controller's container at `/etc/ssl/certs/my-CA.crt` using a Kubernetes `volume` + `volumeMount`.
